name:             doctest
version:          0.17
synopsis:         Test interactive Haskell examples
description: |
  The doctest program checks examples in source code comments.  It is modeled
  after doctest for Python (<http://docs.python.org/library/doctest.html>).

  Documentation is at <https://github.com/sol/doctest#readme>.
category:         Testing
license:          MIT
copyright:        (c) 2009-2018 Simon Hengel
author:           Simon Hengel <sol@typeful.net>
maintainer:       quasicomputational <quasicomputational@gmail.com>


github: sol/doctest

extra-source-files:
- example/**/*
- test/parse/**/*
- test/extract/**/*
- test/integration/**/*
- test/sandbox/*
- CHANGES
- README.markdown

ghc-options: -Wall

dependencies:
- base >= 4.5 && < 5
- base-compat >= 0.7.0
- ghc >= 7.0 && < 9.1
- syb >= 0.3
- code-page >= 0.1
- deepseq
- directory
- filepath
- process
- ghc-paths >= 0.1.0.9
- transformers

when:
  - condition: impl(ghc>=8.11)
    dependencies:
    - exceptions

library:
  source-dirs:
  - src
  - ghci-wrapper/src
  exposed-modules:
  - Test.DocTest

executable:
  main: Main.hs
  ghc-options: -threaded
  source-dirs: driver
  dependencies: doctest

tests:
  spec:
    main: Spec.hs
    ghc-options: -threaded
    cpp-options: -DTEST
    source-dirs:
      - test
      - src
      - ghci-wrapper/src
    c-sources: test/integration/with-cbits/foo.c
    dependencies:
    - HUnit
    - hspec         >= 2.3.0
    - hspec-core    >= 2.3.0
    - QuickCheck    >= 2.13.1
    - stringbuilder >= 0.4
    - silently      >= 1.2.4
    - setenv
    - mockery

  doctests:
    main: doctests.hs
    other-modules: []
    ghc-options: -threaded
    source-dirs: test
    dependencies: doctest
