name:             doctest
version:          0.22.4
synopsis:         Test interactive Haskell examples
description: |
  `doctest` is a tool that checks [examples](https://www.haskell.org/haddock/doc/html/ch03s08.html#idm140354810775744)
  and [properties](https://www.haskell.org/haddock/doc/html/ch03s08.html#idm140354810771856)
  in Haddock comments.
  It is similar in spirit to the [popular Python module with the same name](https://docs.python.org/3/library/doctest.html).

  Documentation is at <https://github.com/sol/doctest#readme>.
category:         Testing
copyright:        (c) 2009-2024 Simon Hengel
author:           Simon Hengel <sol@typeful.net>
maintainer:       Simon Hengel <sol@typeful.net>


github: sol/doctest

default-extensions:
  - NamedFieldPuns
  - RecordWildCards
  - DeriveFunctor
  - NoImplicitPrelude

extra-source-files:
- example/**/*
- test/parse/**/*
- test/extract/**/*
- test/integration/**/*
- CHANGES.markdown
- README.md

ghc-options: -Wall

when:
  - condition: impl(ghc >= 9.0)
    ghc-options: -fwarn-unused-packages

  - condition: impl(ghc >= 9.8)
    ghc-options: -fno-warn-x-partial

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs:
    - src
  exposed-modules:
    - Test.DocTest
    - Test.DocTest.Internal.Extract
    - Test.DocTest.Internal.Location
    - Test.DocTest.Internal.Parse
    - Test.DocTest.Internal.Run

  dependencies: &dependencies
    ghc: ">= 8.0 && < 9.12"
    syb: ">= 0.3"
    code-page: ">= 0.1"
    deepseq:
    directory:
    exceptions:
    filepath:
    process:
    ghc-paths: ">= 0.1.0.9"
    transformers:

executable:
  main: driver/doctest.hs
  ghc-options: -threaded
  dependencies:
    - doctest

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    ghc-options: -threaded
    cpp-options: -DTEST
    source-dirs:
      - test
      - src
    c-sources: test/integration/with-cbits/foo.c
    dependencies:
      <<: *dependencies
      HUnit:
      hspec: ">= 2.3.0"
      hspec-core: ">= 2.3.0"
      QuickCheck: ">= 2.13.1"
      stringbuilder: ">= 0.4"
      silently: ">= 1.2.4"
      mockery:
