verbatim:
  cabal-version: 2.0

name:             doctest
version:          0.19.0
synopsis:         Test interactive Haskell examples
description: |
  The doctest program checks examples in source code comments.  It is modeled
  after doctest for Python (<https://docs.python.org/3/library/doctest.html>).

  Documentation is at <https://github.com/sol/doctest#readme>.
category:         Testing
license:          MIT
copyright:        (c) 2009-2018 Simon Hengel
author:           Simon Hengel <sol@typeful.net>
maintainer:       quasicomputational@gmail.com, Andreas Abel


github: sol/doctest

tested-with:
- GHC == 7.6.3
- GHC == 7.8.4
- GHC == 7.10.3
- GHC == 8.0.2
- GHC == 8.2.2
- GHC == 8.4.4
- GHC == 8.6.5
- GHC == 8.8.4
- GHC == 8.10.7
- GHC == 9.0.1
- GHC == 9.2.1

extra-source-files:
- example/**/*
- test/parse/**/*
- test/extract/**/*
- test/integration/**/*
- CHANGES.markdown
- README.markdown

ghc-options: -Wall

dependencies:
- base >= 4.5 && < 5
- base-compat >= 0.7.0
- ghc >= 7.0 && < 9.3
- syb >= 0.3
- code-page >= 0.1
- deepseq
- directory
- exceptions
- filepath
- process
- ghc-paths >= 0.1.0.9
- transformers

library:
  source-dirs:
  - src
  - ghci-wrapper/src
  exposed-modules:
  - Test.DocTest

executable:
  main: Main.hs
  ghc-options: -threaded
  source-dirs: driver
  dependencies: doctest

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    ghc-options: -threaded
    cpp-options: -DTEST
    source-dirs:
      - test
      - src
      - ghci-wrapper/src
    c-sources: test/integration/with-cbits/foo.c
    dependencies:
    - HUnit
    - hspec         >= 2.3.0
    - hspec-core    >= 2.3.0
    - QuickCheck    >= 2.13.1
    - stringbuilder >= 0.4
    - silently      >= 1.2.4
    - setenv
    - mockery

  doctests:
    main: doctests.hs
    other-modules: []
    ghc-options: -threaded
    source-dirs: test
    dependencies: doctest
