all: gh-md-toc
	inject < README.template.md > ../README.md

gh-md-toc:
	wget https://raw.githubusercontent.com/ekalinin/github-markdown-toc/656b34011a482544a9ebb4116332c044834bdbbf/gh-md-toc
	chmod +x $@
