all: gh-md-toc
	inject < README.template.md > ../README.md

gh-md-toc:
	wget https://raw.githubusercontent.com/ekalinin/github-markdown-toc/0ccf70d0f49b61895f64bca86793ff8cdb88ad51/gh-md-toc
	chmod +x $@
