dependencies:
  - base == 4.*
  - process

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - ghci-wrapper
      - hspec == 2.*
      - silently
