name: cabal-doctest

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-12
          - windows-latest

    steps:
      - uses: actions/checkout@v4

      - run: ghcup install cabal latest --set
        if: matrix.os == 'macos-12'

      - run: cabal path -v0 --installdir >> $GITHUB_PATH
        if: matrix.os == 'macos-12'

      - run: ghcup install ghc 8.6.5 --no-set

      - run: cabal --version
      - run: cabal path
      - run: cabal update
      - run: cabal install -f cabal-doctest
      - run: cabal doctest

      - run: cabal doctest -w ghc-8.6.5

  cabal-doctest-success:
    needs: build
    runs-on: ubuntu-latest
    if: always() # this is required as GitHub considers "skipped" jobs as "passed" when checking branch protection rules

    steps:
      - run: false
        if: needs.build.result != 'success'
